name = "DiffFusionServer"
uuid = "117087b2-87f9-4369-a30d-c1fcf58cf77c"
authors = ["Sebastian Schlenkrich <sebastian.schlenkrich@frame-consult.de> and contributors"]
version = "0.0.1"

[deps]
DiffFusion = "be7e520c-a8fa-4f26-8f65-6d6d1049182e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
DiffFusion = "0.2, 0.4"
HTTP = "1"
JSON3 = "1"
OrderedCollections = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
