name = "DiffFusionServer"
uuid = "117087b2-87f9-4369-a30d-c1fcf58cf77c"
authors = ["Sebastian Schlenkrich <sebastian.schlenkrich@frame-consult.de> and contributors"]
version = "0.0.1"

[deps]
DiffFusion = "be7e520c-a8fa-4f26-8f65-6d6d1049182e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
